import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { CalendarDays, Clock3, Loader2, MapPin, UserRound, X } from 'lucide-react';
import { Button } from '@project/components/ui/button';
import { Input } from '@project/components/ui/input';
import { Label } from '@project/components/ui/label';
import { BRAND_LOGO } from '@/lib/constants';
import { getMomenceSessions, selectMomenceClass, type MomenceSession } from '@/lib/api';

const EMPTY_FIELDS = { fitnessGoal: '', emergencyContactInfo: '', pregnancyStatus: '', medicalHistory: '', postNatalStatus: '', fnf: '', gender: '', euShoeSize: '', howDidHear: '' };

export default function ClassSchedule() {
  const { memberId = '' } = useParams(); const [search] = useSearchParams(); const navigate = useNavigate();
  const center = search.get('center') || ''; const initialClassType = search.get('classType') || 'Barre';
  const classOptions = /kenkere|copper|plash|bengaluru/i.test(center) ? ['Barre'] : ['Barre', 'Strength Lab', 'powerCycle'];
  const [classType, setClassType] = useState(classOptions.includes(initialClassType) ? initialClassType : classOptions[0]);
  const [sessions, setSessions] = useState<MomenceSession[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [selected, setSelected] = useState<MomenceSession | null>(null); const [fields, setFields] = useState(EMPTY_FIELDS); const [booking, setBooking] = useState(false); const [fieldError, setFieldError] = useState('');
  useEffect(() => { setLoading(true); setSessions([]); setError(''); getMomenceSessions({ center, classType }).then(({ sessions }) => setSessions(sessions)).catch((e) => setError(e instanceof Error ? e.message : 'Could not load classes')).finally(() => setLoading(false)); }, [center, classType]);
  const grouped = useMemo(() => sessions.reduce<Record<string, MomenceSession[]>>((all, session) => { const key = new Date(session.startsAt).toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', timeZone: 'Asia/Kolkata' }); (all[key] ||= []).push(session); return all; }, {}), [sessions]);
  const update = (key: keyof typeof EMPTY_FIELDS, value: string) => setFields((current) => ({ ...current, [key]: value }));
  const submit = async () => {
    if (!selected) return; setBooking(true); setFieldError('');
    try {
      const result = await selectMomenceClass({ memberId: Number(memberId), sessionId: selected.id, center, classType, customerFields: fields });
      if (result.checkoutUrl) { window.location.assign(result.checkoutUrl); return; }
      navigate('/success', { state: { city: /bengaluru|copper|kenkere|sadashivnagar/i.test(center) ? 'bengaluru' : 'mumbai', booked: true, session: selected, center } });
    } catch (e) { setFieldError(e instanceof Error ? e.message : 'Could not book this class.'); } finally { setBooking(false); }
  };
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b border-border bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><img src={BRAND_LOGO} alt="Physique 57" className="h-10" /><span className="text-[11px] uppercase tracking-[.18em] text-muted-foreground">Member #{memberId}</span></div></header>
    <main className="mx-auto max-w-5xl px-5 py-10">
      <section className="mb-9 rounded-3xl border border-border bg-card p-7"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">{center}</p><h1 className="mt-2 text-4xl font-bold" style={{ fontFamily: "'Playfair Display', serif" }}>Choose your class</h1><p className="mt-3 text-muted-foreground">Choose an available class below. Any applicable introductory payment is shown after you select your class and complete your profile.</p><div className="mt-6 flex flex-wrap gap-2">{classOptions.map((option) => <button key={option} type="button" onClick={() => { setLoading(true); setError(''); setClassType(option); }} className={`rounded-full border px-4 py-2 text-sm font-semibold transition ${classType === option ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-background text-muted-foreground hover:text-foreground'}`}>{option}</button>)}</div></section>
      {loading && <div className="flex justify-center py-24"><Loader2 className="h-9 w-9 animate-spin text-primary" /></div>}
      {error && <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-5 text-red-300">{error}</div>}
      {!loading && !error && sessions.length === 0 && <div className="rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground">No upcoming {classType} classes are currently available at this studio.</div>}
      <div className="space-y-9">{Object.entries(grouped).map(([day, items]) => <section key={day}><div className="mb-4 flex items-center gap-3"><h2 className="text-xl font-semibold">{day}</h2><span className="h-px flex-1 bg-border" /></div><div className="grid gap-4">{items.map((session) => { const start = new Date(session.startsAt); const full = session.spotsLeft === 0; return <article key={session.id} className="flex flex-col gap-5 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-center"><div className="flex-1"><h3 className="text-lg font-bold">{session.name}</h3><div className="mt-3 flex flex-wrap gap-4 text-sm text-muted-foreground"><span className="flex items-center gap-1.5"><Clock3 className="h-4 w-4" />{start.toLocaleTimeString('en-IN', { hour: 'numeric', minute: '2-digit', timeZone: 'Asia/Kolkata' })}</span>{session.teacherName && <span className="flex items-center gap-1.5"><UserRound className="h-4 w-4" />{session.teacherName}</span>}<span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" />{session.locationName || center}</span></div>{session.spotsLeft != null && <p className="mt-3 text-xs text-muted-foreground">{session.spotsLeft} places remaining</p>}</div><Button disabled={full} onClick={() => setSelected(session)} className="h-11 px-7">{full ? 'Class full' : 'Select class'}</Button></article>})}</div></section>)}</div>
    </main>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-border bg-card p-6 md:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Complete your profile</p><h2 className="mt-2 text-2xl font-bold">Required before booking</h2><p className="mt-1 text-sm text-muted-foreground">{selected.name} · {new Date(selected.startsAt).toLocaleString('en-IN', { weekday: 'short', day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' })}</p></div><button onClick={() => setSelected(null)} aria-label="Close"><X /></button></div>
      <div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Fitness goal" value={fields.fitnessGoal} onChange={(v) => update('fitnessGoal', v)} /><Field label="Emergency contact number *" value={fields.emergencyContactInfo} onChange={(v) => update('emergencyContactInfo', v)} /><SelectField label="Gender" value={fields.gender} options={['Female','Male','Non-binary','Prefer not to say']} onChange={(v) => update('gender', v)} />{fields.gender === 'Female' && <><SelectField label="Are you currently pregnant? *" value={fields.pregnancyStatus} options={['No','Yes']} onChange={(v) => update('pregnancyStatus', v)} /><SelectField label="Post Natal *" value={fields.postNatalStatus} options={['No','Yes','Not applicable']} onChange={(v) => update('postNatalStatus', v)} /></>}<Field label="Medical history *" value={fields.medicalHistory} onChange={(v) => update('medicalHistory', v)} placeholder="Type None if not applicable" /><Field label="FNF" value={fields.fnf} onChange={(v) => update('fnf', v)} />{/cycle|spin/i.test(selected.name) && <Field label="EU shoe size *" value={fields.euShoeSize} onChange={(v) => update('euShoeSize', v)} />}<Field label="How did you hear about us?" value={fields.howDidHear} onChange={(v) => update('howDidHear', v)} /></div>
      {fieldError && <p className="mt-5 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{fieldError}</p>}<Button onClick={submit} disabled={booking} className="mt-7 h-13 w-full">{booking ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Saving details and booking…</> : 'Confirm class booking'}</Button></div></div>}
  </div>;
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <div><Label className="mb-2 block text-xs uppercase tracking-wider">{label}</Label><Input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /></div>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <div><Label className="mb-2 block text-xs uppercase tracking-wider">{label}</Label><select className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm" value={value} onChange={(e) => onChange(e.target.value)}><option value="">Select…</option>{options.map((option) => <option key={option}>{option}</option>)}</select></div>; }
